theme: jekyll-theme-midnight
title: Windows Setup for DCS Courses 
description: An end to Linux Supremacy. Watch this page for download links and a (hopefully) updated tutorial on setting up your Windows environment.
